# Generated by Django 4.0.4 on 2022-05-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV_Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('Similarity_Percent', models.CharField(max_length=2000)),
                ('Skills', models.CharField(max_length=2000)),
            ],
        ),
    ]
